"""Added bok, kund, beställningar, beställningsdetaljer

Revision ID: ab1d27a6d6f1
Revises: 
Create Date: 2024-01-10 10:03:22.259508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab1d27a6d6f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bok',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titel', sa.String(length=80), nullable=False),
    sa.Column('forfattare', sa.String(length=50), nullable=False),
    sa.Column('isbn', sa.String(length=20), nullable=False),
    sa.Column('pris', sa.Float(), nullable=False),
    sa.Column('lagerantal', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isbn')
    )
    op.create_table('kund',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('namn', sa.String(length=100), nullable=False),
    sa.Column('epost', sa.String(length=120), nullable=False),
    sa.Column('telefonnummer', sa.String(length=20), nullable=False),
    sa.Column('adress', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('epost')
    )
    op.create_table('bestallning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kund_id', sa.Integer(), nullable=False),
    sa.Column('bestallningsdatum', sa.DateTime(), nullable=False),
    sa.Column('leveransstatus', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['kund_id'], ['kund.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bestallnings_detalj',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bestallning_id', sa.Integer(), nullable=False),
    sa.Column('bok_id', sa.Integer(), nullable=False),
    sa.Column('antal', sa.Integer(), nullable=False),
    sa.Column('pris_per_enhet', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['bestallning_id'], ['bestallning.id'], ),
    sa.ForeignKeyConstraint(['bok_id'], ['bok.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bestallnings_detalj')
    op.drop_table('bestallning')
    op.drop_table('kund')
    op.drop_table('bok')
    # ### end Alembic commands ###
